name: 'Compile with OpenWatcom'
description: 'Compiles C code with OpenWatcom.'
inputs:
  target:
    description: 'Target to build'
    default: 'all'
runs:
  using: 'docker'
  image: 'docker://pangbox/openwatcom-action:latest'
  args:
    - ${{ inputs.target }}
